PROGRAM PrintHello(INPUT, OUTPUT);
USES
  DOS;
BEGIN {PrintHello}
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN('Hello world!');
  WRITELN('REQUEST_METHOD IS ', GetEnv('REQUEST_METHOD'));
  WRITELN('QUERY_STRING IS ', GetEnv('QUERY_STRING'));
  WRITELN('CONTENT_LENGTH IS ', GetEnv('CONTENT_LENGTH'));
  WRITELN('HTTP_USER_AGENT IS ', GetEnv('HTTP_USER_AGENT'));
  WRITELN('HTTP_HOST IS ', GetEnv('HTTP_HOST'))
END. {PrintHello}

